name: Lint Commit Messages

on: [pull_request]

jobs:
  lint-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint commit messages
        run: .github/scripts/lint-commit-messages.sh
