name: Lint Commit Messages

# check format of commit messages 

on: [pull_request]

jobs:
  lint-commit-messages:
    name: lint-commit-messages 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint commit messages
        run: .github/scripts/lint-commit-msgs.sh
